# Generated by Django 5.1.15 on 2026-06-05 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('contact', 'Contact'), ('prayer', 'Prayer')], max_length=20)),
                ('message', models.TextField(max_length=4000)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('source_path', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='website_for_kind_701e2f_idx'), models.Index(condition=models.Q(('reviewed_at__isnull', True)), fields=['-created_at'], name='unreviewed_idx')],
            },
        ),
    ]
